// AUTO-GENERATED. DO NOT EDIT. SEE homebot/constants.py.
#define ID_NULL                  ''
#define ID_PAN_POWER             'A'
#define ID_TILT_POWER            'B'
#define ID_SONAR_POWER           'C'
#define ID_ARDUINO_TEMP          'D'
#define ID_IMU_EULER             'E'
#define ID_RECHARGE_POWERDOWN    'F'
#define ID_BATTERY_CHARGE_RATIO  'G'
#define ID_IMU_ACCELEROMETER     'H'
#define ID_IMU_GYROSCOPE         'J'
#define ID_IMU_MAGNETOMETER      'K'
#define ID_LOG                   'L'
#define ID_MOTOR_ACCEL           'M'
#define ID_IMU_CALIBRATION       'N'
#define ID_MOTOR_CALIBRATION     'O'
#define ID_MOTOR_ENCODER         'P'
#define ID_TWIST_DONE            'Q'
#define ID_MOTOR_ERROR           'R'
#define ID_GO_TO_SLEEP           'S'
#define ID_SHUTDOWN              'T'
#define ID_CRASH                 'X'
#define ID_HASH                  'Z'
#define ID_PAN_ANGLE             'a'
#define ID_BUMPER                'b'
#define ID_PAN_SPEED             'c'
#define ID_TILT_ANGLE            'd'
#define ID_EDGE                  'e'
#define ID_STATUS_BUTTON         'f'
#define ID_BATTERY_VOLTAGE       'g'
#define ID_BATTERY_TEMP          'h'
#define ID_IDENTIFY              'i'
#define ID_EXTERNAL_POWER        'j'
#define ID_POWER_BUTTON          'k'
#define ID_LED                   'l'
#define ID_LED_AUTO              'm'
#define ID_MOTOR_SPEED           'n'
#define ID_GO_TO_CENTER          'o'
#define ID_PING                  'p'
#define ID_GET_VALUE             'q'
#define ID_PAN_FULL_REV_COUNT    'r'
#define ID_ALL_STOP              's'
#define ID_CALIBRATE             't'
#define ID_ULTRASONIC            'u'
#define ID_PONG                  'v'
#define ID_FORCE_SENSORS         'w'
#define ID_TWIST                 'x'
#define ID_PAN_CENTERMARK        'y'
#define ID_SET_VALUE             'z'
#define NAME_HEAD                "HEAD"
#define NAME_PAN                 "PAN"
#define NAME_TILT                "TILT"
#define NAME_TORSO               "TORSO"
#define METERS_PER_COUNT         0.0001893340385288726
#define TORSO_TREAD_WIDTH_METERS 0.1
#define VELOCITY_TO_SPEED        728.5714285714287
#define SPEED_TO_VELOCITY        0.001372549019607843
#define MOVEMENT_ERROR_NONE      0
#define MOVEMENT_ERROR_EDGE      1
#define MOVEMENT_ERROR_ULTRASONIC 2
#define MOVEMENT_ERROR_TILT      3
#define MOVEMENT_ERROR_ACCEL     4
#define MOVEMENT_ERROR_ENCODER   5
#define MOVEMENT_ERROR_BUMPER    6
#define MOVEMENT_ULTRASONIC_THRESHOLD_CM 5
#define MOVEMENT_MAX_TILT        10
