# http://wiki.ros.org/diagnostics/Tutorials/Configuring%20Diagnostic%20Aggregators
# Run with: 
#   roslaunch ros_homebot diagnostics.launch
#   rosrun rqt_robot_monitor rqt_robot_monitor
pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
#  motors:
#    type: GenericAnalyzer
#    path: Motors
#    startswith: 'motor'
  sensors:
    type: AnalyzerGroup
    path: Sensors
    analyzers:
#      base_hk:
#        type: GenericAnalyzer
#        path: Base Hokuyo
#        timeout: 5.0
#        find_and_remove_prefix: base_hokuyo_node
#        num_items: 3
#      tilt_hk:
#        type: GenericAnalyzer
#        path: Tilt Hokuyo
#        timeout: 5.0
#        find_and_remove_prefix: tilt_hokuyo_node
#        num_items: 3
      imu:
        type: GenericAnalyzer
        path: IMU
        timeout: 5.0
        find_and_remove_prefix: imu_node
        num_items: 3
  computers:
    type: AnalyzerGroup
    path: Computers
    analyzers:
        rpi:
            type: GenericAnalyzer
            path: Raspberry Pi 3
            contains:
            -   'CPU Usage'
            -   'CPU Temperature'
            -   'Disk Usage'
            -   'Memory Usage'
        head_arduino:
            type: GenericAnalyzer
            path: Head Arduino
            timeout: 5.0
            contains:
            -   'Head Arduino'
        torso_arduino:
            type: GenericAnalyzer
            path: Torso Arduino
            timeout: 5.0
            contains:
            -   'Torso Arduino'
#  joints:
#    type: GenericAnalyzer
#    path: Joints
#    startswith: 'Joint'
#  power:
#    type: GenericAnalyzer
#    path: 'Power System'
#    timeout: 5.0
#    startswith: [
#      'Smart Battery',
#      'Power board']
#    expected: [
#      'IBPS 1',
#      'IBPS 2',
#      'IBPS 3',
#      'IBPS 0']
