#!/bin/bash
set -e

clear

[ ! -f src/ID.h ] && ln -s ../../common/src/ID.h src/ID.h
[ ! -f src/SerialPort.h ] && ln -s ../../common/src/SerialPort.h src/SerialPort.h
[ ! -f src/ArduinoTemperatureSensor.h ] && ln -s ../../common/src/ArduinoTemperatureSensor.h src/ArduinoTemperatureSensor.h
[ ! -f src/ChangeTracker.h ] && ln -s ../../common/src/ChangeTracker.h src/ChangeTracker.h
[ ! -f src/EEPROMAnything.h ] && ln -s ../../common/src/EEPROMAnything.h src/EEPROMAnything.h
[ ! -f src/StringUtils.h ] && ln -s ../../common/src/StringUtils.h src/StringUtils.h

[ ! -d lib/Wire ] && ln -s ../../common/lib/Wire lib

ano clean
ano build
#./upload
#./serial

#TODO:fix? upload does nothing?
#arduino --verify --board arduino:avr:uno --port /dev/ttyACM0 test_torso_io.ino
#arduino --upload --board arduino:avr:uno --port /dev/ttyACM0 test_torso_io.ino
