inherits: all

hosts: ['localhost']

is_local: true

project_home: .
homebot_project_dir: .

ros_update_bash: false

services:
-   arduino
#-   avahi
#-   rpi
#-   avahi
#-   nm
#-   mail
-   ros

#nm_check_enabled: true
