#!/bin/bash
# Builds the overlay workspace for containing third-party code
# we don't want to commit locally.
# This version is for running on the deployment host, which doesn't need to build ARM-only packages. e.g. raspicam
set -e

_CURRENT_DIR=$(builtin cd "`dirname "${BASH_SOURCE[0]}"`" > /dev/null && pwd)
_ROS_VERSION=kinetic

if [ -f "$_CURRENT_DIR/setup_local.bash" ]; then
    . $_CURRENT_DIR/setup_local.bash
fi

source /opt/ros/$_ROS_VERSION/setup.bash

cd ..
mkdir -p overlay/src
cd overlay/src

# Added dependencies here.
[ ! -d rpi_gpio ] && git clone https://github.com/chrisspen/rpi_gpio.git rpi_gpio
[ ! -d raspicam_node ] && git clone https://github.com/chrisspen/raspicam_node.git raspicam_node

#source /opt/ros/kinetic/setup.bash
cd ..
# 2018-4-27 CS By default, catkin_make builds everything in our overlay, but we want to exclude certain packages.
# The only way to do this is by specifying on the packages to build.
#catkin_make
catkin_make --pkg ros_qr_tracker
catkin_make --pkg rpi_gpio
